name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: self-hosted
    environment: docker.lab50
    env:
      DOCKER_HOST: tcp://docker1.lab50:2375
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t 1cedo .

      - name: Run tests
        run: docker run --rm 1cedo python3 manage.py test

      - name: Deploy
        run: |
          docker rm -f 1cedo || true
          docker run -d --name 1cedo \
            --restart unless-stopped \
            --network default \
            -e DJANGO_DEBUG=${{ vars.DJANGO_DEBUG }} \
            -e DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} \
            -e CSRF_TRUSTED_ORIGINS=${{ vars.CSRF_TRUSTED_ORIGINS }} \
            --label "traefik.enable=true" \
            --label "traefik.http.routers.1cedo.rule=Host(\`edo.lab50.net\`)" \
            --label "traefik.docker.network=traefik_network" \
            1cedo
          docker network connect traefik_network 1cedo
